# Generated by Django 5.1.7 on 2025-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0003_remove_inventory_warehouse_remove_route_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
