# Generated by Django 5.1.7 on 2025-03-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0006_order_category_order_item_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='logistics_app.vehicle'),
        ),
    ]
