# Generated by Django 5.1.7 on 2025-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0007_order_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default=None, editable=False, max_length=100, unique=True),
        ),
    ]
