# Generated by Django 5.1.7 on 2025-03-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0008_alter_shipment_delivered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofdelivery',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='delivery_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed Delivery')], default='delivered', max_length=10),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('online', 'Online Payment'), ('cod', 'Cash on Delivery'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='proof_photos/'),
        ),
    ]
