# Generated by Django 5.1.7 on 2025-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0009_proofofdelivery_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofdelivery',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofofdelivery',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
