# Generated by Django 5.1.7 on 2025-03-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0010_alter_proofofdelivery_delivered_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='delivered_date',
        ),
    ]
