# Generated by Django 5.1.7 on 2025-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0011_remove_shipment_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
