# Generated by Django 5.1.7 on 2025-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='shipped', max_length=20),
        ),
    ]
