# Generated by Django 5.1.7 on 2025-03-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0013_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofdelivery',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='logistics_app.shipment'),
        ),
    ]
